# Get-ChildItem -Recurse -Depth 2 -File | Select-Object FullName
# mkdocs gh-deploy
# mkdocs serve | build

site_name: Backend Document (lekhraj Dinkar) 2025
site_description: Technical Documentation
site_author: lekhraj Dinkar

extra_javascript:
  - mkdocs.js

# docs_dir: .
# Navigation based on your Notes folder
nav:
  - Docker:
        - Architecture: 02_docker/00_architecture.md
        - Commands / Dev guide: 02_docker/00_dev_guide.md
        - Docker Compose: 02_docker/01_docker-compose.md
        - Storage: 02_docker/03_Storage.md
        - Networking: 02_docker/04_network.md
  - Kubernetes:
      - Start: 03_Kubernetes/index.md
      - ‚úÖMinikube:
          - Introduction: 03_Kubernetes/01_minikube/01_miniKube-1-start.md
          - Hands on: 03_Kubernetes/01_minikube/02_minikube-2-handson.md
      - ‚úÖCore Concepts:
          - k8s Architecture: '03_Kubernetes/02_KCAD/00_00_k8s-architcture+features.md'
          - Containers: '03_Kubernetes/02_KCAD/00_01_container-d.md'
          - Namespaces: '03_Kubernetes/02_KCAD/00_02_Namespace.md'
          - Labels & Selectors: '03_Kubernetes/02_KCAD/00_03_label+selectors.md'
          - Controllers: '03_Kubernetes/02_KCAD/00_04_controller.md'
      - ‚úÖPods:
          - Pod Basics: '03_Kubernetes/02_KCAD/02_01_pod.md'
          - Pod Placement: '03_Kubernetes/02_KCAD/02_02_pod_placement.md'
          - Monitoring & Debugging: '03_Kubernetes/02_KCAD/02_03_pod_monitor+debug.md'
          - Readiness & Liveness: '03_Kubernetes/02_KCAD/02_05_pod_readiness+liveness.md'
          - Resource Management: '03_Kubernetes/02_KCAD/02_06_pod_resource.md'
          - Pod Disruption Budget: '03_Kubernetes/02_KCAD/02_07_pod_PDB.md'
      - ‚úÖWorkloads:
          - StatefulSets: '03_Kubernetes/02_KCAD/03_01_Statefulsets.md'
          - ReplicaSets: '03_Kubernetes/02_KCAD/03_02_replicaSet.md'
          - Jobs / cronjob: '03_Kubernetes/02_KCAD/03_03_jobs.md'
          - DaemonSets: '03_Kubernetes/02_KCAD/03_04_deamonSet.md'
          - Deployment: '03_Kubernetes/02_KCAD/04_deployment_1.md'
          - Deployment (EKS): '03_Kubernetes/04_EKS/03_EKS_Developer-Deployment.md'
          - HPA (EKS): '03_Kubernetes/04_EKS/03_EKS_Developer-01-HPA.md'
      - ‚úÖNetworking:
          - Services: '03_Kubernetes/02_KCAD/05_01_services.md'
          - Ingress: '03_Kubernetes/02_KCAD/05_02_ingress.md'
          - Network Policies: '03_Kubernetes/02_KCAD/05_03_network-policies.md'
      - ‚úÖStorage:
          - Volumes: '03_Kubernetes/02_KCAD/06_01_volume.md'
          - Storage Classes: '03_Kubernetes/02_KCAD/06_02_storage-class.md'
      - ‚úÖSecurity:
          - Secrets: '03_Kubernetes/02_KCAD/07-00-Secrets.md'
          - ConfigMaps: '03_Kubernetes/02_KCAD/07_00-configMap.md'
          - Service Accounts: '03_Kubernetes/02_KCAD/07_00_service-Account.md'
          - Authentication: '03_Kubernetes/02_KCAD/07_01-Authentication.md'
          - kubeconfig Files: '03_Kubernetes/02_KCAD/07_02-kubeConfig-file.md'
          - API Groups: '03_Kubernetes/02_KCAD/07_03-API-Group.md'
          - Authorization: '03_Kubernetes/02_KCAD/07_04-Authorization.md'
          - Cluster Roles: '03_Kubernetes/02_KCAD/07_06-Cluster-roles.md'
          - Admission Controllers: '03_Kubernetes/02_KCAD/07_07-Admission-controller.md'
      - ‚úÖAdvanced Topics:
          - API Versions: '03_Kubernetes/02_KCAD/98_01-API-version.md'
          - Custom Resource Definitions: '03_Kubernetes/02_KCAD/98_02-CRD.md'
      - ‚úÖCKAD Preparation:
          - Exam Topics: '03_Kubernetes/02_KCAD/99_00_CKAD_topic.md'
          - Labs: '03_Kubernetes/02_KCAD/99_01_lab.md'
          - Commands Cheatsheet: '03_Kubernetes/02_KCAD/99_02_commands.md'
      - ‚≠ïEKS:
          - Cluster Setup: 03_Kubernetes/04_EKS/02_01_EKS_Cluster.md
          - Add User + SA: 03_Kubernetes/04_EKS/02_02_EKS-AddUser+ServiceAcct.md
          - Nodegroup + Fargate: 03_Kubernetes/04_EKS/02_03_nodegroup+fargateProfile.md
          - Developer guide:
              - Start: 03_Kubernetes/04_EKS/03_EKS_Developer-00-start.md
              - multi tenant Cluster: 03_Kubernetes/04_EKS/99_CG-MCP-cluster.md
              - Ingress Annotation: 03_Kubernetes/04_EKS/99_CG_annotation-ingress.md
              - Pod Annotation: 03_Kubernetes/04_EKS/99_CG_annotation-Pod.md
              - SA Annotation: 03_Kubernetes/04_EKS/99_CG_annotation-sa.md
              - External Secret: 03_Kubernetes/04_EKS/99_CG_Ext-secret.md
              - IRSA: 03_Kubernetes/04_EKS/99_CG_IRSA.md

      - ‚≠ïHelm:
          - Helm Chart Kickoff: 03_Kubernetes/05_helm/01_helm-chart-kickoff.md

  - Terraform:
      - DevOps: 04_terraform/00_devOps.md
      - start: 04_terraform/01-kickoff.md
      - HCL: 04_terraform/02-HCL.md
      - Modules: 04_terraform/03_module.md

  - CD pipeline:
      - bash: 05_harness/00_bash_script_1.md
      - harness delegates: 05_harness/02_delegates.md
      - harness setup: 05_harness/00_pre_work.md
      - project 1 pipeline: 05_harness/01_pipeline_1.md
      - project 2 pipeline: 05_harness/01_pipeline_2.md
      - project 3 pipeline: 05_harness/01_pipeline_3.md

  - AWS:
      - ‚úîÔ∏è AWS Compute:
          - "EC2": 01_aws/01_compute/01_EC2.md
          - "ECS": 01_aws/01_compute/02_Containers_ECS.md
          - "EKS": 01_aws/01_compute/02_Kubernetes_EKS.md
          - "Lambda Intro": 01_aws/01_compute/03_lambda-01-saa.md
          - "Lambda CLI": 01_aws/01_compute/03_lambda-dva-01-CLI.md
          - "Lambda Triggers": 01_aws/01_compute/03_lambda-dva-02-trigger.md
          - "Lambda Event/Context": 01_aws/01_compute/03_lambda-dva-03-context+event.md
          - "App Runner": 01_aws/01_compute/04_AppRunner.md
          - "Step Functions": 01_aws/01_compute/28_1_STEP_FUNCTION_DVA.md

      - ‚úîÔ∏è AWS Storage:
          - "S3 Basics": 01_aws/02_storage/03_S3-1.md
          - "S3 Advanced": 01_aws/02_storage/03_S3-2-more.md
          - "EBS & EFS": 01_aws/02_storage/01_EBS_EFS.md
          - "FSx": 01_aws/02_storage/02_FSx_serverless-FS.md
          - "Snow Family": 01_aws/02_storage/02_snow-family.md

      - ‚úîÔ∏è AWS Database:
          - "RDS": 01_aws/03_database/01_RDS.md
          - "Aurora": 01_aws/03_database/02_RDS_Aurora.md
          - "DynamoDB SSA": 01_aws/03_database/04_1_DynamoDB_SSA.md
          - "DynamoDB Ops": 01_aws/03_database/04_3_DynamoDB_DVA-operations.md
          - "DAX": 01_aws/03_database/05_DAX.md

      - ‚úîÔ∏è Queues topics streams:
            - "SQS": 01_aws/05_decoupling/01_SQS.md
            - "SNS": 01_aws/05_decoupling/02_SNS.md
            - "KDS": 01_aws/05_decoupling/03_01_KDS_KinesisDataStream.md
            - "KDF": 01_aws/05_decoupling/03_02_KDF_KinesisDataFirehose.md
            - "Active MQ": 01_aws/05_decoupling/04_active_MQ.md
            - "EventBridge": 01_aws/05_decoupling/05_eventBridge.md
            - "MSK": 01_aws/05_decoupling/06_MSK.md

      - ‚úîÔ∏è AWS Networking:
            - "VPC 1": 01_aws/04_network/03_VPC-1-start.md
            - "VPC 2 NAT": 01_aws/04_network/03_VPC-2-NAT.md
            - "VPC 3 VPC-peer vpce": 01_aws/04_network/03_VPC-3-vpcPeer+vpce.md
            - "VPC 4 topologies": 01_aws/04_network/03_VPC-4-tolologies.md
            - "ENI + SG": 01_aws/04_network/00_eni+securityGroup.md
            - "ELB": 01_aws/04_network/01_ELB.md
            - "CloudFront": 01_aws/04_network/04_CloudFront.md
            - "CloudFront(DVA)": 01_aws/04_network/04_CloudFront_DVA.md
            - "global Accelerator": 01_aws/04_network/04_global_Acceleartor.md
            - "API Gateway SAA": 01_aws/04_network/05_1_API_gateway_SAA.md
            - "API Gateway DVA": 01_aws/04_network/05_2_API_gateway_DVA.md
            - "RAM": 01_aws/04_network/06_RAM.md
            #- "Questions-1": 01_aws/04_network/99_Questions-1.md
            - "Route 53": 01_aws/04_network/02_Rout53.md

      - ‚úîÔ∏è AWS Security:
          - "IAM": 01_aws/06_Security/01_IAM.md
          - "SSO & DirectoryService": 01_aws/06_Security/01_SSO+DirectoryService.md
          - "cognito_SAA": 01_aws/06_Security/02_1_cognito_SAA.md
          - "KMS SSA": 01_aws/06_Security/04_1_KMS_SSA.md
          - "KMS DVA": 01_aws/06_Security/04_2_KMS_DVA-cli.md
          - "Secrets Manager": 01_aws/06_Security/06_secret_manager.md
          - "SSM-param-store": 01_aws/06_Security/05_SSM-param-store.md
          - "ACM": 01_aws/06_Security/07_ACM.md
          - "WAF+FirewallManager": 01_aws/06_Security/08_WAF+FirewallManager.md
          - "AWS Sheild": 01_aws/06_Security/09_sheild.md
          - "HSM DVA": 01_aws/06_Security/10_HSM_DVA.md
          - "more": 01_aws/06_Security/99_more.md

      - ‚úîÔ∏è AWS Monitoring:
          - "CloudWatch Metrics": 01_aws/07_monitoring/01_CW-Metric.md
          - "CloudWatch Logs": 01_aws/07_monitoring/02_CW-Logs.md
          - "X-Ray": 01_aws/07_monitoring/04_X-rays_DVA.md
          - "CloudTrail": 01_aws/07_monitoring/05_cloudTrail.md

      - ‚úîÔ∏è AWS DR & Migration:
          - "DR Strategies": 01_aws/09_DR/01_dr-strategies.md
          - "Migration Part 1": 01_aws/09_DR/02_migration-1.md
          - "Migration Part 2": 01_aws/09_DR/02_migration-2.md

      - ‚úÖ AWS Analytics:
          - "Athena": 01_aws/08_Analytics/01_athena_adhocSQL_serverless.md
          - "Redshift": 01_aws/08_Analytics/02_Redshift_OLAP.md
          - "QuickSight": 01_aws/08_Analytics/05_QuickSight_dashboard.md
          - "Glue ETL": 01_aws/08_Analytics/06_glue_ETL.md

      - ‚úîÔ∏è AWS DVA-C02:
          - "DVA Overview": 01_aws/00_DVA-C02/00_DVA.md
          - "CLI & SDK": 01_aws/00_DVA-C02/12_CLI_SDK_more.md
          - "CloudFormation": 01_aws/00_DVA-C02/18_CLOUD_FORMATION.md
          - "CI/CD": 01_aws/00_DVA-C02/24_CI_CD.md
          - "SAM": 01_aws/00_DVA-C02/25_SAM.md
          - "CDK": 01_aws/00_DVA-C02/26_CDK.md
          - "Handson": 01_aws/00_DVA-C02/99_handson.md

      - AWS Practice:
          - "Practice Test": 01_aws/practice-test/index.md

  - Java:
      - Java 7: 00_java/01_java-7-basic.md
      - Java 8: 00_java/02_Java-8-new.md
      - Java 9-11: 00_java/03_Java-9-11-new.md
      - Java 11-17: 00_java/04_Java-11-17-new.md
      - Java 17-21: 00_java/05_Java-17-21-new.md

  - Spring boot:
      - 00 lombok mvn git: 00_Springboot/00_others.md
      - 01 Spring Core:
          - Spring Core Basics: 00_Springboot/01_Spring-core/01_Spring_Core.md
          - Spring Bean Lifecycle: 00_Springboot/01_Spring-core/02_Spring_bean_lifeCycle.md
          - AOP Concept: 00_Springboot/01_Spring-core/03_AOP_concept.md
          - Point-cut Examples: 00_Springboot/01_Spring-core/03_point-cut-examples.txt
          - Spring Properties: 00_Springboot/01_Spring-core/04_spring_properties.md

      - 02 Spring Boot:
          - Kickoff: 00_Springboot/01_springboot/01_SB_kickoff.md
          - Auto Configuration: 00_Springboot/01_springboot/02_SB_AutoConfig.md
          - Starter & Testing: 00_Springboot/01_springboot/03_SB_starter_test.md

      - 03 Web:
          - Web Start: 00_Springboot/02_web/00 WEB_start.md
          - General Web Tasks: 00_Springboot/02_web/00_general_web_task.md
          - Servlet 3: 00_Springboot/02_web/01_servlet_3.md
          - Spring MVC: 00_Springboot/02_web/02_spring_MVC.md
          - Spring Boot Starter Web: 00_Springboot/02_web/03_spring_boot_stater_web.md
          - REST: 00_Springboot/02_web/04_REST.md
          - Jackson: 00_Springboot/02_web/05_Jackson.md
          - Swagger: 00_Springboot/02_web/06_swagger.md
          - Error Handling: 00_Springboot/02_web/07_error_handling.md
          - gRPC & Webflux: 00_Springboot/02_web/08_gRPC+webflux.md
          - Webflux: 00_Springboot/02_web/09_webflux.md

      - 04 Data Layer:
          - Common Tasks: 00_Springboot/03_data-layer/00_common_task.md
          - JPA: 00_Springboot/03_data-layer/01_JPA.md
          - Persistence Context: 00_Springboot/03_data-layer/02_presistence-context.md
          - Hibernate Annotations & Converter: 00_Springboot/03_data-layer/04_Hibernate-1-anno+converter.md
          - Hibernate Identifier & Validator: 00_Springboot/03_data-layer/04_Hibernate-2-identifier+validator.md
          - Hibernate Query: 00_Springboot/03_data-layer/04_Hibernate-3-query.md
          - SB JPA Data Part 1: 00_Springboot/03_data-layer/05-SBjpaData-1-start.md
          - SB JPA Data Part 2: 00_Springboot/03_data-layer/05-SBjpaData-2.md
          - SB JPA Data Transactions: 00_Springboot/03_data-layer/05-SBjpaData-3-txn.md
          - ER Diagram: 00_Springboot/03_data-layer/er-diagram.png

      - 05 Security:
          - OAuth 2.0: 00_Springboot/04_security/00_OAuth_2.0.md
          - Spring Boot Security Start: 00_Springboot/04_security/01_sb-security-start.md
          - Authentication: 00_Springboot/04_security/02_Authentication.md
          - Authorization: 00_Springboot/04_security/03_Authorization.md
          - REST Security: 00_Springboot/04_security/04_REST-secure.md

      - 06 ETL SpringBatch:
          - index: 00_Springboot/05_spring-batch-ETL/00_index.md
          - SpringBatch: 00_Springboot/05_spring-batch-ETL/01_SpringBatch-start.md

  - Messaging:
      - Messaging Protocols: 06_messaging/01_messaging_protocols.md
      - ‚úÖKafka:
          - Getting Started: 06_messaging/kakfa/Notes_01-start.md
          #- CLI Commands (.sh): 06_messaging/kakfa/Notes_02-cli.sh
          - Extended Notes: 06_messaging/kakfa/Notes_04_extended.md
          - Wikimedia Project: 06_messaging/kakfa/Notes_03_project_wikimedia.md
          - Case Studies: 06_messaging/kakfa/Notes_05_case-studies.md
      - ‚úÖRabbitMQ:
          - Kickoff: 06_messaging/rmq/01_kickoff.md
          - project-1(java): 06_messaging/rmq/02_project.md

  - Database:
      - Postgres RDBMS:
          - start: 08_Database/01_rdbms/00_postgress.md
          - Data Types: 08_Database/01_rdbms/01_datatype.md
          - Constraints: 08_Database/01_rdbms/02_constraints.md
          - Normalization: 08_Database/01_rdbms/00_Normalization.md
          - Index: 08_Database/01_rdbms/00_index.md
          - DDL: 08_Database/01_rdbms/02_ddl.md
          - DML: 08_Database/01_rdbms/02_dml.md
          - DQL: 08_Database/01_rdbms/02_dql.md
          - DCL: 08_Database/01_rdbms/03_dcl.md
          - ACID & Locks: 08_Database/01_rdbms/07_ACID+Locks.md
          - Functions: 08_Database/01_rdbms/04_function.md
          - CTE: 08_Database/01_rdbms/05_CTE.md
          - Views: 08_Database/01_rdbms/06_view.md
          - partitioning: 08_Database/01_rdbms/10_partitioning.md
          - Sharding: 08_Database/01_rdbms/10_sharding-rdbms.md
          - Project-01 (Shopping App) : 08_Database/01_rdbms/shopping_app/readme.md

  - Architecture:
      - ‚úÖWeb Security:
          - OAuth & OIDC: 10_Architecture/01_web_Security/03_OAUth+OIDC.md
          - SAML: 10_Architecture/01_web_Security/02_SAML.md
          - Public Key Infrastructure (PKI): 10_Architecture/01_web_Security/01_PKI.md
      - ‚úÖModern Web:
          - üîπwebapp tech-stack: 10_Architecture/02_web_modern/03_webapp_tech_stack.md
          - üîπwebapp design-pattern: 10_Architecture/02_web_modern/03_webapp_design_patterns.md
          - üîπwebapp coding-pattern: 10_Architecture/02_web_modern/03_webapp_coding_patterns.md
          - üî∏API design: 10_Architecture/02_web_modern/04_API_design.md
          - üî∏Database design: 10_Architecture/02_web_modern/06_Database_design.md
          - üî∏K8s design pattern : 10_Architecture/02_web_modern/07_K8s_design_pattern.md
      - ‚úÖMicro services:
          - monolith: 10_Architecture/03_Miscroservice/00_monolith_vs_ms.md
          - Design Patterns: 10_Architecture/03_Miscroservice/01_ms_design_pattern.md
          - Communication: 10_Architecture/03_Miscroservice/03_ms_comm.md
          - Deployment: 10_Architecture/03_Miscroservice/04_ms_deployment.md
          - Container orchestration: 10_Architecture/03_Miscroservice/02_ms_orchestration.md
          - CAP theorem: 10_Architecture/02_web_modern/00_CAP.md
          - 12-Factor App: 10_Architecture/02_web_modern/00_12_factor_app.md
          - üî∫B2B design: 10_Architecture/02_web_modern/02_B2B_design.md
          - üî∫B2C design: 10_Architecture/02_web_modern/02_B2C_design.md
      - ‚úÖProject 1:
          - Design Patterns: 10_Architecture/50_PROJ-1/01-PROJ-1_Design-patterns.md
          - Disaster Recovery: 10_Architecture/50_PROJ-1/02_PROJ-1_DR.md
          - Release Process: 10_Architecture/50_PROJ-1/03_PROJ-1_release_process.md
          - API Overview: 10_Architecture/50_PROJ-1/04_PROJ-1_API.md
          - Observability: 10_Architecture/50_PROJ-1/05_PROJ-1_Observability.md
          - Distributed & Scalable Design: 10_Architecture/50_PROJ-1/06_PROJ-1_Distribted-Scalable.md

  - Observability:
      - Kickoff: 100_observability/00_project.md
      - Springboot: 100_observability/01_Observability-spring.md
      - Datadog: 100_observability/02_observabilty-datadog.md
      - Datadog Agent Config (YAML): 100_observability/datadog-agent.yaml

  #- Career Docs:
      #- Skills: 99_temp/00/01_resume_old.md
      #- Profiles: 99_temp/00/02_profiles.md
      #- Achievements & Learnings: 99_temp/00/97_achievement+learnings.md
      #- Behavioural Prep: 99_temp/00/98_behavioural.md
      #- Interview Q&A: 99_temp/00/99_interview.md
      #- Resumes:
          #- SE-2: 99_temp/00/lekhraj Dinkar-SE-2.pdf
          #- SE-3: 99_temp/00/lekhraj Dinkar-SE-3.pdf
          #- SSE/SE-4: 99_temp/00/lekhraj Dinkar-sse-se4.pdf

extra_css:
  - mkdocs.css

theme:
  name: material
  features:
    #- content.code.annotate
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: pink


repo_url: https://github.com/lekhrajdinkar/02-backend-pack
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  #- markdownextradata
  #- simple-hooks:
      #hooks:
        #on_post_build: "copy_extra_files.copy_yaml_files"

#copyfiles:
  #- deployment/manifest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/
