# Get-ChildItem -Recurse -Depth 2 -File | Select-Object FullName
# mkdocs gh-deploy
# mkdocs serve | build

site_name: System Engineering 2025
site_description: Technical Documentation
nav:
  - Docker:
        - Architecture: 02_docker/00_architecture.md
        - Commands / Dev guide: 02_docker/00_dev_guide.md
        - Docker Compose: 02_docker/01_docker-compose.md
        - Storage: 02_docker/03_Storage.md
        - Networking: 02_docker/04_network.md
  - Kubernetes:
      - Start: 03_Kubernetes/index.md
      - ‚úÖMinikube:
          - Introduction: 03_Kubernetes/01_minikube/01_miniKube-1-start.md
          - Hands on: 03_Kubernetes/01_minikube/02_minikube-2-handson.md
      - ‚úÖCore Concepts:
          - k8s Architecture: '03_Kubernetes/02_KCAD/00_00_k8s-architcture+features.md'
          - Containers: '03_Kubernetes/02_KCAD/00_01_container-d.md'
          - Namespaces: '03_Kubernetes/02_KCAD/00_02_Namespace.md'
          - Labels & Selectors: '03_Kubernetes/02_KCAD/00_03_label+selectors.md'
          - Controllers: '03_Kubernetes/02_KCAD/00_04_controller.md'
      - ‚úÖPods:
          - Pod Basics: '03_Kubernetes/02_KCAD/02_01_pod.md'
          - Pod Placement: '03_Kubernetes/02_KCAD/02_02_pod_placement.md'
          - Monitoring & Debugging: '03_Kubernetes/02_KCAD/02_03_pod_monitor+debug.md'
          - Readiness & Liveness: '03_Kubernetes/02_KCAD/02_05_pod_readiness+liveness.md'
          - Resource Management: '03_Kubernetes/02_KCAD/02_06_pod_resource.md'
          - Pod Disruption Budget: '03_Kubernetes/02_KCAD/02_07_pod_PDB.md'
      - ‚úÖWorkloads:
          - StatefulSets: '03_Kubernetes/02_KCAD/03_01_Statefulsets.md'
          - ReplicaSets: '03_Kubernetes/02_KCAD/03_02_replicaSet.md'
          - Jobs / cronjob: '03_Kubernetes/02_KCAD/03_03_jobs.md'
          - DaemonSets: '03_Kubernetes/02_KCAD/03_04_deamonSet.md'
          - Deployment: '03_Kubernetes/02_KCAD/04_deployment_1.md'
          - Deployment (EKS): '03_Kubernetes/04_EKS/03_EKS_Developer-Deployment.md'
          - HPA (EKS): '03_Kubernetes/04_EKS/03_EKS_Developer-01-HPA.md'
      - ‚úÖNetworking:
          - Services: '03_Kubernetes/02_KCAD/05_01_services.md'
          - Ingress: '03_Kubernetes/02_KCAD/05_02_ingress.md'
          - Network Policies: '03_Kubernetes/02_KCAD/05_03_network-policies.md'
      - ‚úÖStorage:
          - Volumes: '03_Kubernetes/02_KCAD/06_01_volume.md'
          - Storage Classes: '03_Kubernetes/02_KCAD/06_02_storage-class.md'
      - ‚úÖSecurity:
          - Secrets: '03_Kubernetes/02_KCAD/07-00-Secrets.md'
          - ConfigMaps: '03_Kubernetes/02_KCAD/07_00-configMap.md'
          - Service Accounts: '03_Kubernetes/02_KCAD/07_00_service-Account.md'
          - Authentication: '03_Kubernetes/02_KCAD/07_01-Authentication.md'
          - kubeconfig Files: '03_Kubernetes/02_KCAD/07_02-kubeConfig-file.md'
          - API Groups: '03_Kubernetes/02_KCAD/07_03-API-Group.md'
          - Authorization: '03_Kubernetes/02_KCAD/07_04-Authorization.md'
          - Cluster Roles: '03_Kubernetes/02_KCAD/07_06-Cluster-roles.md'
          - Admission Controllers: '03_Kubernetes/02_KCAD/07_07-Admission-controller.md'
      - ‚úÖAdvanced Topics:
          - API Versions: '03_Kubernetes/02_KCAD/98_01-API-version.md'
          - Custom Resource Definitions: '03_Kubernetes/02_KCAD/98_02-CRD.md'
      - ‚úÖCKAD Preparation:
          - Exam Topics: '03_Kubernetes/02_KCAD/99_00_CKAD_topic.md'
          - Labs: '03_Kubernetes/02_KCAD/99_01_lab.md'
          - Commands Cheatsheet: '03_Kubernetes/02_KCAD/99_02_commands.md'
      - ‚≠ïEKS:
          - Cluster Setup: 03_Kubernetes/04_EKS/02_01_EKS_Cluster.md
          - Add User + SA: 03_Kubernetes/04_EKS/02_02_EKS-AddUser+ServiceAcct.md
          - Nodegroup + Fargate: 03_Kubernetes/04_EKS/02_03_nodegroup+fargateProfile.md
          - Developer guide:
              - Start: 03_Kubernetes/04_EKS/03_EKS_Developer-00-start.md
              - multi tenant Cluster: 03_Kubernetes/04_EKS/99_CG-MCP-cluster.md
              - Ingress Annotation: 03_Kubernetes/04_EKS/99_CG_annotation-ingress.md
              - Pod Annotation: 03_Kubernetes/04_EKS/99_CG_annotation-Pod.md
              - SA Annotation: 03_Kubernetes/04_EKS/99_CG_annotation-sa.md
              - External Secret: 03_Kubernetes/04_EKS/99_CG_Ext-secret.md
              - IRSA: 03_Kubernetes/04_EKS/99_CG_IRSA.md

      - ‚≠ïHelm:
          - Helm Chart Kickoff: 03_Kubernetes/05_helm/01_helm-chart-kickoff.md

  - Terraform:
      - DevOps: 04_terraform/00_devOps.md
      - start: 04_terraform/01-kickoff.md
      - HCL: 04_terraform/02-HCL.md
      - Modules: 04_terraform/03_module.md

  - CD pipeline:
      - bash: 05_harness/00_bash_script_1.md
      - harness delegates: 05_harness/02_delegates.md
      - harness setup: 05_harness/00_pre_work.md
      - project 1 pipeline: 05_harness/01_pipeline_1.md
      - project 2 pipeline: 05_harness/01_pipeline_2.md
      - project 3 pipeline: 05_harness/01_pipeline_3.md

  - AWS:
      - ‚úîÔ∏è AWS Compute:
          - "EC2": 01_aws/01_compute/01_EC2.md
          - "ECS": 01_aws/01_compute/02_Containers_ECS.md
          - "EKS": 01_aws/01_compute/02_Kubernetes_EKS.md
          - "Lambda Intro": 01_aws/01_compute/03_lambda-01-saa.md
          - "Lambda CLI": 01_aws/01_compute/03_lambda-dva-01-CLI.md
          - "Lambda Triggers": 01_aws/01_compute/03_lambda-dva-02-trigger.md
          - "Lambda Event/Context": 01_aws/01_compute/03_lambda-dva-03-context+event.md
          - "App Runner": 01_aws/01_compute/04_AppRunner.md
          - "Step Functions": 01_aws/01_compute/28_1_STEP_FUNCTION_DVA.md

      - ‚úîÔ∏è AWS Storage:
          - "S3 Basics": 01_aws/02_storage/03_S3-1.md
          - "S3 Advanced": 01_aws/02_storage/03_S3-2-more.md
          - "EBS & EFS": 01_aws/02_storage/01_EBS_EFS.md
          - "FSx": 01_aws/02_storage/02_FSx_serverless-FS.md
          - "Snow Family": 01_aws/02_storage/02_snow-family.md

      - ‚úîÔ∏è AWS Database:
          - "RDS": 01_aws/03_database/01_RDS.md
          - "Aurora": 01_aws/03_database/02_RDS_Aurora.md
          - "DynamoDB SSA": 01_aws/03_database/04_1_DynamoDB_SSA.md
          - "DynamoDB Ops": 01_aws/03_database/04_3_DynamoDB_DVA-operations.md
          - "DAX": 01_aws/03_database/05_DAX.md

      - ‚úîÔ∏è Queues topics streams:
            - "SQS": 01_aws/05_decoupling/01_SQS.md
            - "SNS": 01_aws/05_decoupling/02_SNS.md
            - "KDS": 01_aws/05_decoupling/03_01_KDS_KinesisDataStream.md
            - "KDF": 01_aws/05_decoupling/03_02_KDF_KinesisDataFirehose.md
            - "Active MQ": 01_aws/05_decoupling/04_active_MQ.md
            - "EventBridge": 01_aws/05_decoupling/05_eventBridge.md
            - "MSK": 01_aws/05_decoupling/06_MSK.md

      - ‚úîÔ∏è AWS Networking:
            - "VPC 1": 01_aws/04_network/03_VPC-1-start.md
            - "VPC 2 NAT": 01_aws/04_network/03_VPC-2-NAT.md
            - "VPC 3 VPC-peer vpce": 01_aws/04_network/03_VPC-3-vpcPeer+vpce.md
            - "VPC 4 topologies": 01_aws/04_network/03_VPC-4-tolologies.md
            - "ENI + SG": 01_aws/04_network/00_eni+securityGroup.md
            - "ELB": 01_aws/04_network/01_ELB.md
            - "CloudFront": 01_aws/04_network/04_CloudFront.md
            - "CloudFront(DVA)": 01_aws/04_network/04_CloudFront_DVA.md
            - "global Accelerator": 01_aws/04_network/04_global_Acceleartor.md
            - "API Gateway SAA": 01_aws/04_network/05_1_API_gateway_SAA.md
            - "API Gateway DVA": 01_aws/04_network/05_2_API_gateway_DVA.md
            - "RAM": 01_aws/04_network/06_RAM.md
            #- "Questions-1": 01_aws/04_network/99_Questions-1.md
            - "Route 53": 01_aws/04_network/02_Rout53.md

      - ‚úîÔ∏è AWS Security:
          - "IAM": 01_aws/06_Security/01_IAM.md
          - "SSO & DirectoryService": 01_aws/06_Security/01_SSO+DirectoryService.md
          - "cognito_SAA": 01_aws/06_Security/02_1_cognito_SAA.md
          - "KMS SSA": 01_aws/06_Security/04_1_KMS_SSA.md
          - "KMS DVA": 01_aws/06_Security/04_2_KMS_DVA-cli.md
          - "Secrets Manager": 01_aws/06_Security/06_secret_manager.md
          - "SSM-param-store": 01_aws/06_Security/05_SSM-param-store.md
          - "ACM": 01_aws/06_Security/07_ACM.md
          - "WAF+FirewallManager": 01_aws/06_Security/08_WAF+FirewallManager.md
          - "AWS Sheild": 01_aws/06_Security/09_sheild.md
          - "HSM DVA": 01_aws/06_Security/10_HSM_DVA.md
          - "more": 01_aws/06_Security/99_more.md

      - ‚úîÔ∏è AWS Monitoring:
          - "CloudWatch Metrics": 01_aws/07_monitoring/01_CW-Metric.md
          - "CloudWatch Logs": 01_aws/07_monitoring/02_CW-Logs.md
          - "X-Ray": 01_aws/07_monitoring/04_X-rays_DVA.md
          - "CloudTrail": 01_aws/07_monitoring/05_cloudTrail.md

      - ‚úîÔ∏è AWS DR & Migration:
          - "DR Strategies": 01_aws/09_DR/01_dr-strategies.md
          - "Migration Part 1": 01_aws/09_DR/02_migration-1.md
          - "Migration Part 2": 01_aws/09_DR/02_migration-2.md

      - ‚úÖ AWS Analytics:
          - "Athena": 01_aws/08_Analytics/01_athena_adhocSQL_serverless.md
          - "Redshift": 01_aws/08_Analytics/02_Redshift_OLAP.md
          - "QuickSight": 01_aws/08_Analytics/05_QuickSight_dashboard.md
          - "Glue ETL": 01_aws/08_Analytics/06_glue_ETL.md

      - ‚úîÔ∏è AWS DVA-C02:
          - "DVA Overview": 01_aws/00_DVA-C02/00_DVA.md
          - "CLI & SDK": 01_aws/00_DVA-C02/12_CLI_SDK_more.md
          - "CloudFormation": 01_aws/00_DVA-C02/18_CLOUD_FORMATION.md
          - "CI/CD": 01_aws/00_DVA-C02/24_CI_CD.md
          - "SAM": 01_aws/00_DVA-C02/25_SAM.md
          - "CDK": 01_aws/00_DVA-C02/26_CDK.md
          - "Handson": 01_aws/00_DVA-C02/99_handson.md

      - AWS Practice:
          - "Practice Test": 01_aws/practice-test/index.md

  - MessageBroker:
      - Messaging Protocols: 06_message-broker/01_messaging_protocols.md
      - More: 06_message-broker/02_more.md
      - ‚úÖKafka:
          - Getting Started: 06_message-broker/kakfa/Notes_01-start.md
          - Extended Notes: 06_message-broker/kakfa/Notes_04_extended.md
          - Wikimedia Project: 06_message-broker/kakfa/Notes_03_project_wikimedia.md
          - Case Studies: 06_message-broker/kakfa/Notes_05_case-studies.md
      - ‚úÖRabbitMQ:
          - Kickoff: 06_message-broker/rmq/01_kickoff.md
          - project-1(java): 06_message-broker/rmq/02_project.md


  - Observability:
      - Kickoff: 09_observability/00_kick_off.md
      - Spring boot: 09_observability/01_Observability-spring.md
      - Datadog: 09_observability/02_observabilty-datadog.md
      #- Datadog Agent Config (YAML): 09_observability/datadog-agent.yaml

  - üíªSystem Design:
      - Theorem and Patterns ‚òëÔ∏è:
          - CAP: 10_System_Design/SD_00_theorum+patterns/00_CAP.md
          - tech_stack: 10_System_Design/SD_00_theorum+patterns/00_tech_stack.md
          - concepts: 10_System_Design/SD_00_theorum+patterns/03_concepts.md
      - High performance ‚òëÔ∏è:
          - Start: 10_System_Design/SD_01_performance/01_start.md
      - High Availability ‚òëÔ∏è:
          - Start: 10_System_Design/SD_02_Availability/01_start.md
      - Scalability ‚òëÔ∏è:
          - services: 10_System_Design/SD_03_scalability/01-services.md
          - Database: 10_System_Design/SD_03_scalability/02-db+storage.md
          - Microservices:
              - monolith: 10_System_Design/SD_03_scalability/micro-service/00_monolith_vs_ms.md
              - microservice comm: 10_System_Design/SD_03_scalability/micro-service/03_ms_comm.md
              - Deployment: 10_System_Design/SD_03_scalability/micro-service/04_ms_deployment.md
              - Container orchestration: 10_System_Design/SD_03_scalability/micro-service/02_ms_orchestration.md
              - API design 1: 10_System_Design/SD_03_scalability/micro-service/03_01_API.md
              - API design 2: 10_System_Design/SD_03_scalability/micro-service/03_02_API.md
      - Reliability ‚òëÔ∏è:
          - resilient: 10_System_Design/SD_04_reliability/01_resiliency-1.md
          - durable: 10_System_Design/SD_04_reliability/02_durability-1.md
      - Distributed system ‚òëÔ∏è:
          - Start: 10_System_Design/SD_05_Distributed/01_distributed-start.md
      - Observability ‚òëÔ∏è:
          - Start: 10_System_Design/SD_06_obs/01_Obs_start.md
      - Security ‚òëÔ∏è:
          - JWT: 10_System_Design/SD_07_security/01_start.md
          - OAuth2.0 & OIDC: 10_System_Design/SD_07_security/04_03_OAUth+OIDC.md
          - SAML: 10_System_Design/SD_07_security/04_02_SAML.md
          - Public Key Infrastructure (PKI): 10_System_Design/SD_07_security/04_01_PKI.md
      - Database + storage ‚òëÔ∏è:
          - Start: 10_System_Design/SD_08_Storage+database/01_start.md
          - Design Patterns: 10_System_Design/SD_08_Storage+database/02_design_patterns.md

      - ‚úÖSystems:
          - System-1(app-6) ‚òëÔ∏è:
              - B2B model: 10_System_Design/SD_99_Examples/app-6/00_PROJ-1_B2B.md
              - Design Patterns: 10_System_Design/SD_99_Examples/app-6/01-PROJ-1_Design-patterns.md
              - Disaster Recovery: 10_System_Design/SD_99_Examples/app-6/02_PROJ-1_DR.md
              - Release Process: 10_System_Design/SD_99_Examples/app-6/03_PROJ-1_release_process.md
              - API Overview: 10_System_Design/SD_99_Examples/app-6/04_PROJ-1_API.md
          - byte-byte-go ‚òëÔ∏è:
              - 101 rate limiting: 10_System_Design/SD_99_Examples/byte-byte-go/101_rate-limiter.md
              - 110 notification system: 10_System_Design/SD_99_Examples/byte-byte-go/110_notification-system.md
          - byteMonk ‚òëÔ∏è:
              - byteMonk_reference: 10_System_Design/SD_99_Examples/byteMonk/00_byteMonk_reference.md

extra_css:
  - mkdocs.css

theme:
  name: material
  features:
    #- content.code.annotate
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    #- navigation.expand
    - navigation.indexes
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: grey
      accent: pink


repo_url: https://github.com/lekhrajdinkar/solution-engineer
repo_name: GitHub
edit_uri: edit/main/Notes/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/

